services:
  monkey-island-custom-config:
    restart: unless-stopped
    networks:
      - remnawave-network
    image: monkey-island-custom-config:v0.1
    env_file:
      - .env
    privileged: true
    volumes:
      - log:/app/log
    build:
      context: ..
      dockerfile: docker/Dockerfile

volumes:
  log:

networks:
  remnawave-network:
    external: true
